### ISSUE TITLE
Personal Statement

### ISSUE THREAD

**Issue by lewismcgeary** [derwinmcgeary/derwinmcgeary.github.io#2]
Order - switch second and third paragraphs.
Who I am
What I want
What I bring.

 "I'm passionate about helping people understand and learn, and conveying technical knowledge in an accessible way."
Very teachery. Change for non teaching jobs

"And I'm ready to work for you" controversial

**Comment by derwinmcgeary** [comment]
I'll leave the teachery bit since the holy trinity in data science is coding/maths/communication.
